# Generated by Django 4.1.2 on 2022-10-12 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_equipe_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('feature', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(max_length=200, verbose_name='Descrição da ferramenta')),
                ('icon', models.CharField(choices=[('lni-rocket', 'foguete'), ('lni-laptop-phone', 'leptop'), ('lni-cog', 'engrenagem'), ('lni-leaf', 'folha1'), ('lni-layers', 'template'), ('lni-leaf', 'folha2')], max_length=16, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
            },
        ),
    ]
